futground/urls.py
from django.urls import path
from .import views


app_name = 'futground'


urlpatterns = [
     path('home/', views.home, name='fut-home'),
     path('list/', views.list, name='fut-list'),
     path('search/', views.search, name='fut-search'),
     path('search/list/futground/<int:ground_id>/', views.detail, name='fut-searchdetail'),
     path('list/futground/<int:ground_id>/', views.detail, name='fut-detail'),
     path('list/futground/<int:reservation_id>/delete/',views.deletereservation,name='fut-delete'),
     #path('list/futground/<int:ground_id>/khalti/', views.khalti, name='fut-khalti'),

     path('recommend/', views.recommend, name='fut-recommend'),
     path('recommned/list/futground/<int:ground_id>/', views.detail, name='fut-recommenddetail'),
     path('rate/<int:ground_id>/', views.rate, name='fut-rate'),

]

futsalproj/urls.py
from django.contrib import admin
from django.urls import include,path
#from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('register/',user_views.register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('',include('futground.urls')),
    path('',include('users.urls')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .import views

urlpatterns = [
     path('register/', views.register,name='register'),
]

futground/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User



class Ground(models.Model):
    name = models.CharField(max_length=1000)
    location = models.CharField(max_length=1000)
    longitude = models.FloatField(null=True)
    latitude = models.FloatField(null=True)
    contact = models.IntegerField(default= 0)
    price = models.IntegerField(default=1500)
    photo = models.ImageField(max_length=255,upload_to='futground/media',blank=True,null=True)
    #photo1 = models.ImageField()
    #photo2 = models.ImageField()

    def __str__(self):
        return self.name

    class Meta:
        ordering=['name']
class Reservation(models.Model):
    user = models.IntegerField()
    ground = models.ForeignKey(Ground,on_delete=models.CASCADE)
    starting_time = models.TimeField()
    ending_time = models.TimeField()
    reserved_date = models.DateField()

    class Meta:
        ordering = ["reserved_date","starting_time","ending_time"]

    def __str__(self):
        return  str(self.reserved_date)


class Rating(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    ground = models.ForeignKey(Ground,on_delete=models.CASCADE)
    rate = models.IntegerField(blank=True)
    avg_rating= models.FloatField(default=0.0,blank=True)
    num_rate = models.IntegerField(default=0,blank=True)

    def __str__(self):
          return str(self.user)+ "--" + str(self.ground) +"--"+ str(self.rate) + " -- " +str(self.avg_rating) +"--"+ str(self.num_rate)

futground/forms.py
from django import forms
from django.forms import ModelForm
from futground.models import Reservation,Ground,Rating
from django.contrib.auth.models import User


class UserReservationForm(forms.Form):
    ground = forms.ModelChoiceField(queryset=Ground.objects.all())
    starting_time = forms.TimeField()
    ending_time = forms.TimeField()
    reserved_date = forms.DateField()

    class Meta:
        model = Reservation
        fields = ['ground', 'starting_time', 'ending_time', 'reserved_date']


class RatingForm(forms.Form):
       user = forms.ModelChoiceField(queryset=User.objects.all())
       ground = forms.ModelChoiceField(queryset=Ground.objects.all())
       rate = forms.IntegerField(min_value=1,max_value=5)

       class Meta:
           model= Rating
           fields=['user','ground','rate']

futground/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from futground.models import Ground,Reservation,Rating
from .forms import UserReservationForm,RatingForm
from django.contrib.auth.models import User
from django.contrib import messages
from datetime import date
from django.utils.dateparse import parse_date
from datetime import timedelta
from django.db.models import Q
import random
import math


def home(request):
    return render(request, 'futground/home.html')


def evaluate_cosine_similarity(user,similar_user):
    numerator = 0
    user_square_sum = 0
    similar_user_square_sum = 0

    for i in range(len(user)-1):
        numerator = numerator + (user[i]*similar_user[i])
        user_square_sum = user_square_sum + (user[i]*user[i])
        similar_user_square_sum = similar_user_square_sum + (user[i]*user[i])

    denominator = math.sqrt(user_square_sum) + math.sqrt(similar_user_square_sum)
    similarity = numerator/denominator
    return similarity


def predict_user_item_rating(user,similar_user,cosine_similarity):
    denominator = 0
    predictate_rating = []

    similar_user_average = []
    user_average = 0

    for i in range(len(cosine_similarity)):
        denominator = denominator + cosine_similarity[i]

    for i in range(len(similar_user)):
        average = 0;
        total = 0;
        for j in range(len(similar_user[0])):
            total = total + similar_user[i][j]
        average = total/len(similar_user[0])
        similar_user_average.append(average)

    total = 0
    for i in range(len(user)):
        total = total + user[i]
    user_average  = total/len(user)

    for j in range(len(similar_user[0])):
        numerator = 0
        for i in range(len(similar_user)):
            numerator = numerator + ((similar_user[i][j]-similar_user_average[i])*cosine_similarity[i])
        predict = user_average + (numerator/denominator)
        predictate_rating.append(predict)

    return predictate_rating

def removingDuplicates(listOfElements):
    uniqueList = []

    for elem in listOfElements:
        if elem not in uniqueList:
            uniqueList.append(elem)

    return uniqueList

def similar_ground(user_id):
    user_rated_ground = []
    similar_rating_user_id = []
    similar_user_rated_grounds = []
    rating = Rating.objects.filter(user=user_id)

    #get the grounds rated by active user
    for rating in rating:
        user_rated_ground.append(rating.ground)

    #get the similar users who rated the grounds rated by active user
    similar_rating = Rating.objects.filter(ground__in=user_rated_ground).order_by('user_id').exclude(user_id=user_id)

    #prepare the list of similar rating users and the grounds they rated
    for s in similar_rating:
        similar_rating_user_id.append(s.user_id)

        for h in Rating.objects.filter(user_id=s.user_id):
            similar_user_rated_grounds.append(h.ground_id)

    #print(similar_user_rated_grounds)
    # removing duplicates
    if similar_rating_user_id and similar_user_rated_grounds:
         similar_rating_user_id = removingDuplicates(similar_rating_user_id)
         similar_user_rated_grounds = removingDuplicates(similar_user_rated_grounds)

    similar_rating_user_id.sort()
    similar_user_rated_grounds.sort()

    #create user-item matrix for both active user and similar users
    similar_user =  [[0] * len(similar_user_rated_grounds) for i in range(len(similar_rating_user_id))]
    user = []

    for i,similar_user_id in enumerate(similar_rating_user_id):
        for j,ground_id in enumerate(similar_user_rated_grounds):
            if Rating.objects.filter(user_id=similar_user_id,ground_id=ground_id).exists():
                r = Rating.objects.values('rate').get(user_id=similar_user_id,ground_id=ground_id)
                rate1 = r['rate']
            else:
               rate1 = 0
            similar_user[i][j] = rate1


    for j in similar_user_rated_grounds:
        if Rating.objects.filter(user_id=user_id, ground_id=j).exists():
            r = Rating.objects.values('rate').get(user_id=user_id, ground_id=j)
            rate1 = r['rate']
        else:
            rate1 = 0
        user.append(rate1)

    #calculating similarity through cosine similarity
    cosine_similarity = []

    for i in range(len(similar_rating_user_id)):
        similarity = evaluate_cosine_similarity(user,similar_user[i])
        cosine_similarity.append(similarity)

    ground = []

    if cosine_similarity:
        #predicting the rating for the each item of active user
        predictate_rating = predict_user_item_rating(user,similar_user,cosine_similarity)

        #now finding the top predictate ground rating
        predictate_similar_ground = []
        grounds = []
        for j, ground_id in enumerate(similar_user_rated_grounds):
            predictate_similar_ground.append((ground_id,predictate_rating[j]))
        predictate_similar_ground.sort(key=lambda x  : x[1],reverse=True)

        for p in predictate_similar_ground:
            grounds.append(p[0])

        for h in grounds:
            ground.append( Ground.objects.get(id=h))

    return ground[:10]

@login_required()
def recommend(request):
    if Rating.objects.filter(user=request.user.id).exists():
      similar = similar_ground(request.user.id)
      context = {'ground': similar}
    else:
        messages.info(request, f'cold start,need more ratings')
        return redirect('futground:fut-list')

    return render(request, 'futground/recommendation.html',context)

def list(request):
    all_grounds = Ground.objects.all()


    rating = Rating.objects.values_list('avg_rating','ground').order_by('-avg_rating').distinct()[:5]
    ground = []
    for rating in rating:
        ground.append(int(rating[1]))

    all_ratings = Ground.objects.filter(id__in=ground)

    #similar = similar_ground(request.user.id)
    #print(request.user.id)


    context = {'all_grounds': all_grounds,'all_ratings':all_ratings}
    return render(request, 'futground/list.html', context)


@login_required()
def detail(request, ground_id):
    ground = Ground.objects.get(pk=ground_id)
    user = request.user.id

    if request.method == 'POST' and 'res_btn' in request.POST:
      form1 = UserReservationForm(request.POST)
      gd = request.POST.get('ground')
      st = request.POST.get('starting_time')
      et = request.POST.get('ending_time')
      rd = request.POST.get('reserved_date')
      res = Reservation()
      r = parse_date(rd)

      print(st)
      print(et)
      print(rd)
      print(type(r))


      if r == None or r < date.today() or r > date.today() + timedelta(days=7) or st > et or st < '10:00:00' or et > '18:00:00':
        print("sdas")
        messages.success(request,f'time format mistake')


      elif Reservation.objects.filter(ground=gd,starting_time = st,reserved_date=rd,ending_time = et).exists():
           messages.success(request, f'already reserved time slot')
           #return redirect('futground:fut-detail')

      else:

        if form1.is_valid():
            res.ground = Ground.objects.get(pk=gd)
            res.starting_time = st
            res.ending_time = et
            res.reserved_date = r
            res.user = request.user.id

            res.save()
            messages.success(request, f'successfully reserved')
            return redirect('futground:fut-rate',ground_id)


        else:
         print("form invalid")
         print(form1.errors)




    else:
       form1 = UserReservationForm(initial={'ground': ground_id})

    return render(request,'futground/detail.html',{'ground':ground,'form1':form1,'user_id' : request.user.id})

def deletereservation(request,reservation_id):
    obj = Reservation.objects.get(id=reservation_id)
    print(obj)
    if request.method=="POST":
        obj.delete()
        return redirect('futground:fut-home')
    #context={
     #   "object":obj

    #}
    return render(request,'futground/reservationdelete.html')

@login_required()
def search(request):


    if request.method == 'POST':
      s1 = request.POST.get('srch')
      s = Ground.objects.filter(
                                Q(name__istartswith=s1)
                                )


    return render(request,'futground/search.html',{'s':s})


@login_required()
def rate(request,ground_id):
    ground = Ground.objects.get(pk=ground_id)
    user = request.user.id
    form = RatingForm(request.POST)
    if request.method == 'POST' and 'rt_btn' in request.POST:
        form = RatingForm(request.POST)
        r = Rating()
        rt = request.POST.get('rate')
        rtu = request.POST.get('user')
        rtg = request.POST.get('ground')

        if Rating.objects.filter(user_id=user, ground_id=ground).exists():
            Rating.objects.filter(user_id=user, ground_id=ground).update(rate=rt)
            messages.success(request, f'updated rate')
            return redirect('futground:fut-list')



        elif form.is_valid():
            r.rate = rt
            r.user_id = rtu
            r.ground_id = rtg
            r.save()
            messages.success(request, f'rated')
            return redirect('futground:fut-list')
    else:
      form = RatingForm(initial={'ground': ground_id,'user':request.user.id})

    return render(request, 'futground/rate.html', {'ground': ground, 'form': form, 'user': request.user.id})

#def khalti(request,ground_id):
       #return render(request, 'futground/khalti.html')

futground/templates/futground/base.html
<html>
<head>
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

<!-- jQuery library  for b4 -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>



</head>
<body>
<nav class="navbar navbar-expand-md bg-dark navbar-dark">

  <!-- Toggler/collapsibe Button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Navbar links -->
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
        <li class="nav-item">
        <a class="nav-link" href="#">FutNep</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'futground:fut-home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'futground:fut-list'  %}">Futsal list</a>
      </li>
      {% if user.is_authenticated %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'futground:fut-recommend' %}">Recommendation</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>

      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'register' %}">Registration</a>
      </li>
      {% endif %}
        <form action="{% url 'futground:fut-search' %}" method="POST">
           {% csrf_token %}
              <input type="text" name="srch" placeholder="search">
              <input type='submit' value="search">

      </form>

    </ul>
  </div>
</nav>
<div id="content">
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}}">
    {{ message }}
</div>
{% endfor %}
{% endif %}
<!---{% block photo %}
  {% endblock %} --->
  {% block content %}

{% endblock %}
  </div>
</body>
</html>

futground/templates/futground/detail.html
{% extends 'futground/base.html' %}
{% load staticfiles %}
{% block title %} detail {% endblock %}
{% load static %}
<!---{% block photo %}
<div class="container">
  <img src="{% static 'images/futsal.jpg' %}" width="550" height="435" align="left">
</div>
{% endblock %} --->
{% block content %}
{% if ground.photo %}
  <img src={{ground.photo.url}} height="435",width='50%' align="left">
{% endif %}
<h2> {{ ground.name}}</h2>
<table>
    <tr>
        <th> location :</th>
        <td> {{ground.location }}</td>
    </tr>
    <tr>
        <th> contact :</th>
        <td>{{ground.contact}}</td>
    </tr>
    <tr>
        <th> price  :</th>
        <td> {{ground.price }}</td>
    </tr>
    <tr>
        <th> opens at  :</th>
        <td> 10am to 6pm</td>
    </tr>

</table>

<div id="googleMap" style="width:30%;height:300px;"></div>

<script>

function myMap() {
var mapProp= {
  center:new google.maps.LatLng({{ ground.latitude }},{{ ground.longitude }}),
  zoom:18,
};

var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);
var marker = new google.maps.Marker({
  position:mapProp.center,
  animation:google.maps.Animation.BOUNCE

});

marker.setMap(map);
}
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC7y69WjgbhiFed2G0T1qC8wXr9SMxQjtI&callback=myMap"></script>

<hr>
{% block form %}

{% include 'futground/reservation.html' %}


{% endblock form %}
<h2> reserved date</h2>
<table style="width:100%">
  <tr>
    <th>Starts at</th>
    <th>Ends at</th>
    <th>Date</th>
    <th>Action</th>
  </tr>
{% for g in ground.reservation_set.all %}
    <tr>
        <td>  starting time :{{ g.starting_time }} </td>
        <td>  ending time : {{ g.ending_time }} </td>
        <td>  reserved date :{{ g.reserved_date}}  </td>
        {% now "%H:%M:%S" as time %}
        {% if g.user == user_id %}
        <td> <button><a href="{% url 'futground:fut-delete' g.id %}">cancel</a></button></td>
        {% endif %}
    </tr>
{% endfor %}
{% endblock content %}

futground/templates/futground/home.html
{% extends 'futground/base.html' %}
{% load staticfiles %}
<link rel="stylesheet" text="text/css" href="{% static 'futground/style.css' %}" />
{% block title %} home {% endblock %}
{% block content %}
<html>
<body>
   <img src="{% static '/images/logo.jpg' %}" height="100%" weight="auto">
</body>
</html>
   {% endblock %}

futground/templates/futground/list.html
{% extends 'futground/base.html' %}
{% block title %} list {% endblock %}
{% block content %}
{% if user.is_authenticated %}
<h2> Top rated futsals</h2>
{% if all_ratings %}
{% for r in all_ratings %}

      <li><a href="futground/{{r.id}}/"> {{r.name }} </a></li>

{% endfor %}
{% endif %}
{% endif %}

{% if all_grounds %}
<h3>List of all Futsals</h3>


    {% for ground in all_grounds %}

    <li><a href="futground/{{ground.id}}/"> {{ ground.name }}-{{ ground.location}} </a></li>
    {% endfor %}

{% else %}
 <h3>nothing</h3>
{% endif %}
{% endblock %}

futground/templates/futground/reservation.html
{% load crispy_forms_tags %}

{% block form %}
<h3>RESERVATION</h3>
<form method = "POST">
    {% csrf_token %}
    <div class="form-group">
    {{ form1|crispy }}
   </div>


  <button type="submit" class="btn btn-primary" name="res_btn">Reserve</button>

</form>



    {% endblock %}

futground/templates/futground/reservationdelete.html
{% block content %}

<form action="." method="POST">
    {% csrf_token %}
    <h1> do you want to cancel?</h1>
    <p><input type='submit' value='yes'> <a href="{% url 'futground:fut-list' %}">cancel</a> </p>
</form>

{% endblock %}

futground/templates/futground/search.html
{% extends 'futground/base.html' %}
{% block content %}
<h1> Search result</h1>
{% if s %}
{% for g in s  %}
   <li><a href="list/futground/{{g.id}}/"> {{ g.name }}</a></li>
{% endfor %}
{% else %}
    <h5>No result found</h5>
{% endif %}
{% endblock %}